### ISSUE TITLE
Named Entity Recognition Corpus for organisations or companies names (ORG)

### ISSUE THREAD

**Issue by turnerrainer** [buerokratt/Data-Anonymizer#12]
AS A End-User
I WANT TO have corpus with all mapped Estonian organizations and enterprises
SO THAT anonymiser could automatically identify all the referred entity names from the input text 

### **Acceptance criterias:**

- [x] NER Corpus bases on ORG mapped in the New Estonian NER Corpus

**Comment by vmugra** [comment]
Äriregistri nimede andmed - edastan

**Comment by tarstarkvara** [comment]
Second and third acceptance criteria don't match the profile of corpus building task since these are related to model training. I propose removing those.

**Comment by tarstarkvara** [comment]
Edited myself.

**Comment by tarstarkvara** [comment]
Corpus created, will be uploaded in #23 .
