### ISSUE TITLE
Failure of deploying Data Anonymizer to Riigipilv

### ISSUE THREAD

**Issue by turnerrainer** [buerokratt/Data-Anonymizer#147]
Deploying [Data Anonymizer](https://github.com/buerokratt/Data-Anonymizer) to Riigipilv as a Docker service fails due to not being able to fetch a remote dependency. Deploying on a local computer works fine.

![image](https://user-images.githubusercontent.com/90505798/213035131-4350985b-9731-40e2-be22-b730a9515e85.png)

**Comment by livenson** [comment]
Issue is with MTU, which is 1450 by default in internal net with docker using 1500.
Solutions:

- Option A. Override custom docker mtu globally. Create `/etc/docker/daemon.json` with content like:
```
{
"mtu": 1400
}
```
And restart docker daemon (e.g. `systemctl restart docker`)

- Option B: Override MTU in a specific docker-compose configuration. Less intrusive. Will provide a PR for this one.

**Comment by livenson** [comment]
https://github.com/buerokratt/Data-Anonymizer/pull/148

**Comment by varmoh** [comment]
I ran the updated docer-compose.yml but the error is still present and build fails.
![Screenshot from 2023-01-18 09-25-55](https://user-images.githubusercontent.com/101868197/213109806-3daad33b-8f75-4737-a4e0-8ba3ff10a40a.png)

**Comment by livenson** [comment]
Can you try option B please?

**Comment by varmoh** [comment]
> Can you try option B please?

![Screenshot from 2023-01-18 09-37-08](https://user-images.githubusercontent.com/101868197/213111508-c4678dbe-0646-4257-af98-fb9d03a4d7c6.png)

That is what I did. I did git pull in RPLV, inside the workfolder. I checked just in case the docker-compose.ym,and it had the MTU set as it should be. I ran the command and it produced the error.

**Comment by livenson** [comment]
can you please show output of 'ip l' while docker compose up is running?

**Comment by varmoh** [comment]
I will add screenshots of following things:
ip l command output
curl comand output from inside the container
![Screenshot from 2023-01-18 10-04-49](https://user-images.githubusercontent.com/101868197/213116827-7bed197e-7847-4a53-bbdf-6f0a6272d8bc.png)
![Screenshot from 2023-01-18 10-04-58](https://user-images.githubusercontent.com/101868197/213116852-6c91f86b-14f3-482b-ad24-d128a1b0f5d7.png)

**Comment by varmoh** [comment]
While inside the container, the repo of maven, will hang where you can see it on the screenshot. In the host or while deploying locally, this will not happen

**Comment by varmoh** [comment]
Full cycle of curl from inside the container
![Screenshot from 2023-01-18 10-13-04](https://user-images.githubusercontent.com/101868197/213118338-598bef3d-6acc-4708-af6d-8bb29d470639.png)

**Comment by livenson** [comment]
you have mtu of 1500 on veth interface (261), this is the issue.

Are you building with docker compose or docker build?

**Comment by varmoh** [comment]
@livenson commentary (source outside github)
ok, uurisin natuke sügavam
krdi jama on see docker ikkagi

1. sa kasutasid custom võrgu default võrgu asemel -- nu, ok, võiks töötada
2. võrk peaks olema seadistatud siis build contextis, mitte run contextis -- lisasin selle

3. ikkagi ei tööta, sest docker buildkit nüüd vaikimisi ei luba overridida custom võrgud buildi ajal - põhjendused on githubis olemas, aga mu arust natuke pehmed - viga näeb välja nagu nii: network mode "ruuter" not supported by buildkit - you can define a custom network for your builder using the network driver-opt in buildx create

4. "lahendus" - COMPOSE_DOCKER_CLI_BUILD=1 docker-compose up  # töötab, aga kasutab legacy build meetodi
teine variant, kui tahad ainult git pulli teha, on kasutada default võrku override, nagu pull requestis oli

**Comment by varmoh** [comment]
Update.
I got it to work with docker-compose up -d
Changes that Ilja made work.
I will add the updated yml here and will create a pull request after some further testing.
version: '3.9'
services:
  ruuter:
    container_name: ruuter
    build:
      context: .
      network: ruuter
    volumes:
      - ./DSL:/DSL
    ports:
      - 8080:8080
    networks:
      - ruuter   
networks:
  ruuter:
    name: ruuter
    driver: bridge
    driver_opts:                         
       com.docker.network.driver.mtu: 1400
