### ISSUE TITLE
API JSON is in Estonian 

### ISSUE THREAD

**Issue by vaunapuu** [buerokratt/Data-Anonymizer#164]
The key values in API JSON are in Estonian. Why?
<img width="670" alt="Screenshot 2023-08-30 at 12 53 02" src="https://github.com/buerokratt/Data-Anonymizer/assets/15847415/bb043a33-147d-484a-b82e-fd022b933732">

**Comment by Kristjan259** [comment]
Seems like it is changed now.

<img width="597" alt="Screenshot 2024-11-21 at 16 09 45" src="https://github.com/user-attachments/assets/dd96ada6-2dc9-43f9-b749-a6e8b3c44671">
