### ISSUE TITLE
Dead links

### ISSUE THREAD

**Issue by vaunapuu** [buerokratt/Data-Anonymizer#166]
Clicking on these links will either do nothing or lead to wrong place

1.  In main menu 'Github'
<img width="612" alt="Screenshot 2023-08-30 at 13 27 33" src="https://github.com/buerokratt/Data-Anonymizer/assets/15847415/c27f661f-6d91-4bf5-904d-a2c710302dcd">

2. In https://anonym.demo.buerokratt.ee/treening, click on 'MÄRGENDA TÄIENDAVALT KÄSITSI'
<img width="1266" alt="Screenshot 2023-08-30 at 13 30 15" src="https://github.com/buerokratt/Data-Anonymizer/assets/15847415/7c488819-8ec0-4502-b38d-8e07129863d9">

3. In https://anonym.demo.buerokratt.ee/treening, click on 'Regexi kasutamise kohta loe infot siit lingilt.'
<img width="1179" alt="Screenshot 2023-08-30 at 13 34 26" src="https://github.com/buerokratt/Data-Anonymizer/assets/15847415/98a58a80-604b-442f-96e5-6b5f3339261e">

**Comment by PaulaMerle** [comment]
Tested 21.11.2024, links are working.
