### ISSUE TITLE
Can't delete existing training file

### ISSUE THREAD

**Issue by vaunapuu** [buerokratt/Data-Anonymizer#168]
STEPS:
1. Go to https://anonym.demo.buerokratt.ee/treening
2. Upload a a training file 
3. Click on 'X' to remove training file

EXPECTED RESULT:
Training file is removed

ACTUAL RESULT:
Nothing happens
<img width="913" alt="Screenshot 2023-08-30 at 17 53 40" src="https://github.com/buerokratt/Data-Anonymizer/assets/15847415/9dd623e9-728f-4f12-97c4-8b90c03a0dce">

**Comment by PaulaMerle** [comment]
Tested and fixed (21.11.2024)
