### ISSUE TITLE
Named Entity Recognition Corpus for persons (PER)

### ISSUE THREAD

**Issue by turnerrainer** [buerokratt/Data-Anonymizer#4]
AS A End-User
I WANT TO have corpus with mapped person names (first and last)
SO THAT anonymiser could automatically identify all the persons refferred in the input text 

### **Acceptance criterias:**

- [x] NER Corpus bases on PER mapped in the New Estonian NER Corpus

**Comment by vmugra** [comment]
Nimede andmebaas - Sandril olemas

**Comment by tarstarkvara** [comment]
Second and third acceptance criteria don't match the profile of corpus building task since these are related to model training. I propose removing those.
