### ISSUE TITLE
Label a sentence

### ISSUE THREAD

**Issue by kunnark** [buerokratt/Data-Anonymizer#43]
AS A labeler 
I WANT TO label my sentence according to IOB notation and my added entities
IN ORDER TO prepare my private corpus for the training.

Acceptence Criteria:

- [ ] I can label a sentence if I choose an entity and select a part of the sentence - a word or several words.
- [ ] Labeled sentence is saved to the Postgres database via Ruuter `POST /annotate?project={id}` and ReSQL `POST /upsert_corpora_task queries`

**Comment by turnerrainer** [comment]
@alimuhammadahmer @kunnark this issue is marked as "Done" but I can not see any code commits.

**Comment by turnerrainer** [comment]
@alimuhammadahmer @kunnark ACs must contain API endpoints for both Ruuter and Resql.

**Comment by alimuhammadahmer** [comment]
Ruuter API:
POST /annotate?project={id}
Resql API:
POST /upsert_corpora_task

**Comment by kunnark** [comment]
@turnerrainer Ruuter and ReSQL endpoints added.
