### ISSUE TITLE
Set up Label Studio

### ISSUE THREAD

**Issue by kunnark** [buerokratt/Data-Anonymizer#45]
AS A user 
I WANT TO start labelling my custom corpus 
IN ORDER TO improve my data.

Acceptance Criteria:

- [ ] Label Studio FE been set up and running  
- [ ] Label studio loads the configured corpus from Postgres database on startup

Additional Information:

From the DMI the user selects the corpus so when loading label studio, this information is already present. Basically there has to be a variable that’s used to decide which corpus to load from the Postgres DB.

**Comment by turnerrainer** [comment]
@alimuhammadahmer @kunnark

1. This issue is marked as "Done" but I can not see any code commits;
2. AC must contain REST endpoints;
3. Currently, this issue covers loading a corpus from a Postgres DB but does not mention using Ruuter as a mediator. Is Ruuter currently in use at all?

**Comment by kunnark** [comment]
@turnerrainer I'll cover that.
1. 'Done' is marked because in our statement it's done, but I can remove this back to another state. No commits have been made, due we haven't yet agreed with how to do that, meeting you proposed will happen next week. Should I remove all 'Done' stories back to 'Ready' state at the moment?
2. This story was to set up the Label Studio, no REST endpoints have been developed insofar. The development happens on concrete cases.
3. Will clarify and add that one.

**Comment by turnerrainer** [comment]
@kunnark I marked is as "To Groom" as it needs a bit more attention. There is a need for an automated pipeline here. I'll include our devops as well.

**Comment by turnerrainer** [comment]
@kunnark @alimuhammadahmer 

About the AC.

1. Docker Compose to set up Label Studio locally;
2. I'd like to take a closer look on Label Studio -> Postgres connection as this is most likely something to cause problems for us in the long run in case not done via Ruuter.

**Comment by turnerrainer** [comment]
Although if insertion is always done via Ruuter and Label Studio just reads database on its own then this should be fine. But let's just clear it up here for future reference.

**Comment by alimuhammadahmer** [comment]
@turnerrainer  Both Label Studio and Data Management Frontend Applications always call Ruuter Endpoints. Ruuter, then in turn calls ReSQL endpoints for Data Insertion/Reading, and returns response from it.
