### ISSUE TITLE
Filter sentences by ID

### ISSUE THREAD

**Issue by kunnark** [buerokratt/Data-Anonymizer#47]
AS A labeler
I WANT TO filter my sentences using sentence ID 
IN ORDER TO select sentences that interests me.

Acceptance Criteria:
- [ ] By default no filter is being applied.
- [ ] If I click on a ‘Filter' then I can choose an interval of sentences I can filter ‘is between’.
- [ ] If I click on a ‘Filter’ I can choose a filter that applies ‘bigger than’ > particular ID
- [ ] If I click on a ‘Filter’ I can choose a filter that applies ‘smaller than’ <  particular ID
- [ ] I can also choose filters “>=” and “<=” on particular ID.
- [ ] If I apply on a filter then the condition is being applied on sentence IDs and I can see the particular sentences I have chosen.
- [ ]  If I cancel the filter then the Default View is being applied, no filter is applied to the list of sentences.

**Comment by turnerrainer** [comment]
@alimuhammadahmer @kunnark

1. Is this purely a GUI development?
2. ACs must contain all REST endpoints used, even if it only means GUI making requests to endpoints that will not be developed within this issue.

**Comment by alimuhammadahmer** [comment]
Filtering/Sorting happens on Frontend. No Backend API is involved.

**Comment by kunnark** [comment]
@turnerrainer look at the @alimuhammadahmer 's comment. No backend involved.

**Comment by alimuhammadahmer** [comment]
@kunnark we changed this so that the filtering/sorting now happens on the BE. But the endpoint is the same (Ruuter GET /tasks?project={id} & ReSQL POST /get_corpora) as in https://github.com/buerokratt/Data-Anonymizer/issues/46. So I have linked that particular Pull Request to this story as well.
