### ISSUE TITLE
Train a NER model using new labeled Bürokratt dataset

### ISSUE THREAD

**Issue by kunnark** [buerokratt/Data-Anonymizer#50]
AS A data scientist
I WANT TO train a new NER model 
IN ORDER TO improve the anonymisation results.

Acceptance Criteria:
- [x] New model is trained on Bürokratt new dataset.

**Comment by turnerrainer** [comment]
@tarstarkvara @kunnark this issue is marked as "Done" but I can not see any code commits.

**Comment by tarstarkvara** [comment]
Model trained (since this one was exploratory training then no code upload from this task). Handed over for engineering side to include in API and upload to repo.
