### ISSUE TITLE
Create and upload clean training script

### ISSUE THREAD

**Issue by kunnark** [buerokratt/Data-Anonymizer#51]
AS A developer 
I WANT TO use training script
IN ORDER TO implement training capabilty to the Data Management Interface app.

Acceptance Criteria:
- [ ] Training script is renewd and uploaded to Git.

**Comment by turnerrainer** [comment]
@tarstarkvara @kunnark

1. This issue is marked as "Done" but I can not see any code commits;
2. ACs must contain all REST endpoints used to get the result.

**Comment by turnerrainer** [comment]
@kunnark a bit unclear on what this issue will do.

>/--/
>IN ORDER TO implement training capabilty to the Data Management Interface app

It seems that DMI should make appropriate REST call(s) to Ruuter but no REST endpoints are given.

**Comment by turnerrainer** [comment]
@alimuhammadahmer please refer to an appropriate commit or the file in mention.

**Comment by turnerrainer** [comment]
Close as done by https://github.com/buerokratt/Data-Anonymizer/issues/65
