### ISSUE TITLE
Improve search based component

### ISSUE THREAD

**Issue by kunnark** [buerokratt/Data-Anonymizer#52]
AS a Data Scientist
I WANT TO improve search based component
IN ORDER TO combine the output better with ML approach

Acceptance Criteria:

- [x] Implemented Solution where search-based component is dependent on ML probabilities
- [x] Improved handling of partial matches

**Comment by turnerrainer** [comment]
@kunnark no user story or ACs added but this issue is already in progress by @tarstarkvara

**Comment by kunnark** [comment]
@turnerrainer about DS stories I told in the conversation, we'll clarify them by upcoming Tuesday Nov 15th.

**Comment by tarstarkvara** [comment]
Code handed over to engineering side for including in the API.

**Comment by turnerrainer** [comment]
@tarstarkvara this issue can't be closed as there are no commits related to it.

**Comment by tarstarkvara** [comment]
Since it is data science dev code, we will not be uploading it to the repo.
