### ISSUE TITLE
Improve Regex based component

### ISSUE THREAD

**Issue by kunnark** [buerokratt/Data-Anonymizer#53]
AS a Data Scientist
I WANT TO improve regex based component
IN ORDER TO combine the output better with ML approach and cover all entities

Acceptance Criteria:

- [x] Implemented Solution where regex-based component is dependent on ML probabilities
- [x] created regex for each required entity type

**Comment by turnerrainer** [comment]
@kunnark no user story or ACs added but this issue is already in progress by @tarstarkvara

**Comment by tarstarkvara** [comment]
Code handed over to engineering side for including in the API.

**Comment by turnerrainer** [comment]
@tarstarkvara this issue can't be closed as there are no commits related to it.

**Comment by tarstarkvara** [comment]
Since it is data science dev code, we will not be uploading it to the repo.
