### ISSUE TITLE
Improve Anonymization process performance

### ISSUE THREAD

**Issue by kunnark** [buerokratt/Data-Anonymizer#56]
AS a Data Scientist
I WANT TO improve anonymisation process performance
IN ORDER TO complete the anonymisation process in a more reasonable time

Acceptance Criteria:

- [x]  logic of anonymisation process is reviewed
- [x]  processing logic is imrpoved both tiem and resource wise

**Comment by turnerrainer** [comment]
@kunnark

1. User story does not correspond to the style we have agreed upon;
2. ACs missing completely;
3. Regardless of the above, this issue is already marked as "Ready".

**Comment by tarstarkvara** [comment]
Code handed over to engineering side for including in the API.

**Comment by vmugra** [comment]
@tarstarkvara please commit code as well.

**Comment by turnerrainer** [comment]
@alimuhammadahmer is there a specific commit to relate to this issue?

**Comment by turnerrainer** [comment]
Close as done by https://github.com/buerokratt/Data-Anonymizer/issues/56
