### ISSUE TITLE
Data Management Interface

### ISSUE THREAD

**Issue by kunnark** [buerokratt/Data-Anonymizer#58]
Goal: provide Data Management Interface for uploading a corpus, train a model, pre-label automatically a sentence, label manually and anonymize text.

The epic consists of following stories:
- [x] #61
- [x] #62
- [x] #60
- [x] #59 
- [x] #63
- [x] #64
- [x] #65
- [x] #66
- [x] #69

**Comment by turnerrainer** [comment]
@kunnark user story does not correspond to the style we have agreed upon.

**Comment by kunnark** [comment]
@turnerrainer this is labeled as 'epic' not a user story. Should I use a user-story here as well?
