### ISSUE TITLE
Add new Regex pattern to the database

### ISSUE THREAD

**Issue by kunnark** [buerokratt/Data-Anonymizer#59]
AS A Data Management Interface user
I WANT TO add a new Regex pattern to the database 
IN ORDER TO recognize new entities.

Acceptance Criteria:
- [ ] Single Regex pattern can be added to the Postgres database via Ruuter `POST /regex` and ReSQL `POST /insert_regex`
- [ ] I can map the pattern with the entity given.
- [ ] I can add the pattern via input text box
- [ ] I can map the pattern with appropriate entity from the drop-down selection

Additional Info
Database consists of column with Regex and mapped entity.

Schema
![diagram (4)](https://user-images.githubusercontent.com/5320604/201304306-ed2a2ba4-8173-4373-8c01-8f449efb6e61.svg)

**Comment by turnerrainer** [comment]
@kunnark @alimuhammadahmer 

1. Is this just DSL or GUI development as well?
2. ACs must contain API endpoints for both Ruuter and Resql.

**Comment by alimuhammadahmer** [comment]
Create Regex Mapping Ruuter Endpoint:
POST /regex
Create Regex Mapping Resql Endpoint:
POST /insert_regex

List Regex Mapping Ruuter Endpoint:
GET /regex
List Regex Mapping Resql Endpoint:
POST list_regex

**Comment by kunnark** [comment]
@turnerrainer 
1. GUI AC's also added
2. Endpoints added. BPMN schema added.
