### ISSUE TITLE
View list of Regex patterns added by user

### ISSUE THREAD

**Issue by kunnark** [buerokratt/Data-Anonymizer#60]
AS A Training Module User
I WANT TO see existing regex patterns via GUI
SO I WOULD have an overview of existing ones and a path to manipulate them

### Acceptance Criteria

- [ ] A list of regex patterns is provided by a Ruuter endpoint `GET /regex` via ReSQL `GET list_regex `as a JSON array
- [ ] A list of regex patterns is shown via GUI
- [ ] GUI provides a button to remove any given regex pattern

**Comment by turnerrainer** [comment]
@alimuhammadahmer @kunnark

1. ACs must contain all REST endpoints used to get the result;
2. There are currently a user story with ACs and something similar to a draft user story with some bullet points - remove what's unnecessary.

**Comment by alimuhammadahmer** [comment]
List Regex Mapping Ruuter Endpoint:
GET /regex
List Regex Mapping Resql Endpoint:
POST list_regex

**Comment by kunnark** [comment]
@turnerrainer 
1. AC REST endpoints added
2. Draft deleted
3. You have added and AC- `Any given regex pattern can be removed by calling a specific Ruuter endpoint` Deleting Regex is a separate user story here: https://github.com/buerokratt/Data-Anonymizer/issues/63, will remove this AC.
