### ISSUE TITLE
Set up ReSQL instance

### ISSUE THREAD

**Issue by kunnark** [buerokratt/Data-Anonymizer#62]
AS A developer
I WANT TO  Set up working ReSQL instance 
IN ORDER to develop database applications.

Acceptance Criteria:
- [ ] ReSQL instance is set up and running.

**Comment by turnerrainer** [comment]
@kunnark @alimuhammadahmer as this is an internal task for yourselves then

1. It may but does not have to be on this board;
2. Let it be "Done".
