### ISSUE TITLE
Train a custom model

### ISSUE THREAD

**Issue by kunnark** [buerokratt/Data-Anonymizer#65]
AS A Data Management Interface (DMI) user
I WANT TO  train a custom model on top of my custom dataset 
IN ORDER TO perform anonymization on my custom dataset.

Acceptance Criteria:
- [ ] I can start the training process
- [ ] Current training status can be checked with Ruuter `GET /training_status` 
- [ ] The training process calls training script via Ruuter `POST /train`
- [ ] Training script gets and prepares data for the training getting it from the Postgres database using ReSQL.
- [ ] If training is ‘in progress’ status then new training cannot be started.
- [ ] The new model is saved to the local disk replacing the old one.
- [ ] I can see a newly trained model in UI as the last trained model.
- [ ] I can see a corpus file in UI name that's being used on trained model.

Additional information:
Training schema:
![diagram (2)](https://user-images.githubusercontent.com/5320604/201303019-ed81f91a-e283-4b7b-90f0-652847f762e5.svg)

**Comment by turnerrainer** [comment]
@alimuhammadahmer @kunnark

1. This issue is marked as "In progress" but should be groomed first;
2. ACs must contain all REST endpoints used to get the result.

**Comment by alimuhammadahmer** [comment]
RUUTER endpoint:
POST /train

**Comment by kunnark** [comment]
@turnerrainer 
> 
> 1. This issue is marked as "In progress" but should be groomed first;
> 2. ACs must contain all REST endpoints used to get the result.

1. Status changed to 'backlog'
2. REST endpoint added to AC.
