### ISSUE TITLE
Automatically pre-label uploaded corpus

### ISSUE THREAD

**Issue by kunnark** [buerokratt/Data-Anonymizer#66]
AS A Data Management Interface user 
I WANT TO trigger ‘pre-labelling’ API endpoint for my corpus 
IN ORDER TO NER-tag my corpus automatically.

### Acceptance Criteria

- [ ] After I have uploaded a my private corpus, I can trigger  ‘Pre-label’ Anonymisation API endpoint via Ruuter
- [ ] After ‘Pre-label’ has been clicked then my corpus is being pre-labelled automatically and NER-tagged and added to the Postgres database via Ruuter and ReSQL.
- [ ] After the NER-tagging process has finalised, I can see my corpus in Labellng Interface NER-tagged and start manual tagging.

**Endpoints**

- [ ] ML endpoint: `/predict`
- [ ] Ruuter endpoint: `POST /annotate_corpora`
- [ ] ReSQL endpoint: `POST /get_latest_corpora`

Table structure:
![Bürokratt-anonüümija-Data Model](https://user-images.githubusercontent.com/5320604/201292816-87940385-593d-4060-9115-45f64ed73617.jpg)

**Comment by turnerrainer** [comment]
@alimuhammadahmer @kunnark 

1. Add a list of all REST endpoints-to-be;
2. Add the description of the database table in use.

**Comment by alimuhammadahmer** [comment]
ML Endpoint:
/predict
Ruuter Endpoint:
POST /preannotate
Resql Endpoint:
POST /preannotate_corpora_task/batch

**Comment by kunnark** [comment]
@turnerrainer 
1. Added Additional information
2. Added schema.

**Comment by turnerrainer** [comment]
@alimuhammadahmer @kunnark in general well done but need to clarify on how 'ML Endpoint /predict` will be triggered. Directly? Via Ruuter?

**Comment by turnerrainer** [comment]
@alimuhammadahmer `ML endpoint: /predict` is POST as well, right? Please update it in AC.
