### ISSUE TITLE
Upload private corpus to the database

### ISSUE THREAD

**Issue by kunnark** [buerokratt/Data-Anonymizer#69]
AS Data Management Interface user
I WANT TO upload my own new private NER corpus from the database 
IN ORDER TO train a new model and teach new entities to the model.

Acceptance Criteria:
- [ ] Get the corpus from the user via uploading module
- [ ] Format and upload private corpus to Postgres database via Ruuter `POST /corpora` and ReSQL `POST /insert_corpora_task/batch`

Additional
We’re getting the corpus through Ruuter. 

IMPORTANT
Ruuter does not handle file uploads at the moment, so we should solve this by mocking the upload itself. Request comes in, nothing is actually uploaded, and the process uses a specific demo file already existing on disk. This is a Ruuter limitation that will be solved in the future, but is not solved yet.

Uploading corpus schema
![diagram (3)](https://user-images.githubusercontent.com/5320604/201303807-0da4cb75-baec-4eaa-a128-6b1cc5b9581d.svg)

**Comment by turnerrainer** [comment]
@alimuhammadahmer @kunnark

1. This issue is marked as "In progress" but should be groomed first;
2. ACs must contain all REST endpoints used to get the result.

**Comment by alimuhammadahmer** [comment]
Ruuter Endpoint:
POST /corpora
Resql Endpoint:
POST /insert_corpora_task/batch

**Comment by kunnark** [comment]
@turnerrainer 
> 
> 1. This issue is marked as "In progress" but should be groomed first;
> 2. ACs must contain all REST endpoints used to get the result.

1. Status changed to 'Backlog'
2. AC's added endpoints, bpmn-schema added.
