### ISSUE TITLE
Upload NER Corpus to GitHub repository

### ISSUE THREAD

**Issue by kunnark** [buerokratt/Data-Anonymizer#71]
AS a Data Scientist
I WANT TO upload new ner corpus
IN ORDER TO make it available for public usage

Acceptance Criteria:

- [ ]  New corpus is uploaded

**Comment by turnerrainer** [comment]
@kunnark 

1. User story is missing completely;
2. ACs are missing completely;
3. Regardless of the above, this issue is already marked as "Ready".

**Comment by kunnark** [comment]
@turnerrainer my bad I took it from https://github.com/buerokratt/Data-Anonymizer/issues/26 and it's obsolete marked by you.

**Comment by turnerrainer** [comment]
Closing this issue as we ended up using https://huggingface.co/buerokratt
