### ISSUE TITLE
CI/CD pipeline for NER models training and validation in local server

### ISSUE THREAD

**Issue by kunnark** [buerokratt/Data-Anonymizer#72]

**Comment by turnerrainer** [comment]
@kunnark 

1. User story is missing completely;
2. ACs are missing completely.

**Comment by kunnark** [comment]
@turnerrainer this one is a copy from your initial backlog with no AC's added https://github.com/buerokratt/Data-Anonymizer/issues/42 but probably necessary to do.

**Comment by tarstarkvara** [comment]
@kunnark you sure this one is for me?

**Comment by turnerrainer** [comment]
This is a poor issue (by our side). Closing it as the expected result is provided.
