### ISSUE TITLE
Make script to upload a new public NER corpus

### ISSUE THREAD

**Issue by kunnark** [buerokratt/Data-Anonymizer#73]
AS A Anonymiser Application user 
I WANT TO execute the command line script 
IN ORDER TO upload the public NER corpus to Github.

Acceptance Criteria:
- [ ] Script can be executed via command line
- [ ] Script connects to ReSQL via Ruuter and gets the NER corpus.
- [ ] Corpus is formatted according to Git requirements.
- [ ] Script uploads the corpus to Git via `PUT https://api.github.com/repos/${GIT_OWNER}/${GIT_REPO}/contents/corpus_${corporaId}.json`

**Comment by turnerrainer** [comment]
@alimuhammadahmer @kunnark

1. This issue is marked as "Done" but I can not see any code commits;
2. ACs must contain all REST endpoints used to get the result.

**Comment by alimuhammadahmer** [comment]
GIT upload Endpoint:
PUT https://api.github.com/repos/${GIT_OWNER}/${GIT_REPO}/contents/corpus_${corporaId}.json

**Comment by turnerrainer** [comment]
Closing this issue as we ended up using https://huggingface.co/buerokratt instead.
