### ISSUE TITLE
Set up Data Model

### ISSUE THREAD

**Issue by kunnark** [buerokratt/Data-Anonymizer#74]
AS A developer
I WANT A data model to be set up
IN ORDER TO start developing the application

Acceptence Criteria:
- [ ] Postgres database described in #75  is set up
- [ ] Data Model is implemented in the database
- [ ] Automatic Data Model CREATE script exists.

**Comment by turnerrainer** [comment]
@alimuhammadahmer @kunnark

1. This issue is marked as "Done" but I can not see any code commits;
2. _"Data Model is implemented in the database"_ --- this should be done by using Liquibase (https://www.liquibase.org/).

**Comment by kunnark** [comment]
@turnerrainer 
> 1. This issue is marked as "Done" but I can not see any code commits;
> 2. _"Data Model is implemented in the database" and "Automatic Data Model CREATE script exists"_ --- these should be implemented by using Liquibase (https://www.liquibase.org/).

1. Status changed
2. As agreed on the call, you will provide a contact of RIA's DevOps engineer and additional details.
