### ISSUE TITLE
Describe Data Model for Application

### ISSUE THREAD

**Issue by kunnark** [buerokratt/Data-Anonymizer#75]
AS A developer 
I WANT TO Describe and make schema of Data Model 
IN ORDER TO start implementing the RIA Anonymiser Application. 

Acceptance Criteria:
-  [ ] model is created and schematically described.

Additional information

We can only use denormalized data schema, no normalized models can be used.

Update and delete commands are prohibited. All the data must have “softly updated and deleted”

We can use Postgres for database.

All queries from FE to BE and between the components need to go through Ruuter [Bürokratt / Plug-and-play / Ruuter · GitLab](https://github.com/buerokratt/Ruuter)

The idea behind denormalization is to make the data simpler to export and to possibly migrate to NoSQL in the future. The Update and Delete restrictions are there to automatically have logs of everything they change. Both restrictions come from the client.

**Comment by turnerrainer** [comment]
@alimuhammadahmer @kunnark https://github.com/buerokratt/Ruuter should be used as Ruuter instead of https://koodivaramu.eesti.ee/buerokratt/plug-and-play/ruuter as mentioned in description.

**Comment by turnerrainer** [comment]
@alimuhammadahmer @kunnark this issue is marked as "Done" but I can not see any code commits.

**Comment by kunnark** [comment]
@turnerrainer 
1. Link changed, internally we have used correct Ruuter instance.
2. Status changed.
