### ISSUE TITLE
Entity Recognition models based on search engine

### ISSUE THREAD

**Issue by kunnark** [buerokratt/Data-Anonymizer#76]
AS a Data Scientist
I WANT TO create logic and initial versions of search-based engine
IN ORDER TO increase recall in finding entities

Acceptance Criteria:

- [x]  Search-based logic is created and handed over to engineering side

**Comment by turnerrainer** [comment]
@kunnark 

1. User story is missing completely;
2. ACs are missing completely;
3. Regardless of the above, this issue is already marked as "In progress".

**Comment by kunnark** [comment]
@turnerrainer this one is a copy from your backlog https://github.com/buerokratt/Data-Anonymizer/issues/15 there was no AC's related insofar but it does need to be developed.

**Comment by vmugra** [comment]
@tarstarkvara please commit models to the repository as well.
