### ISSUE TITLE
Machine-learning-based NER models

### ISSUE THREAD

**Issue by kunnark** [buerokratt/Data-Anonymizer#77]
AS a Data Scientist
I WANT TO create logic and initial versions of ML-based engine
IN ORDER TO increase recall in finding entities

Acceptance Criteria:

- [x]  ML logic is created and handed over to engineering side

**Comment by turnerrainer** [comment]
@kunnark 

1. User story is missing completely;
2. ACs are missing completely;
3. Regardless of the above, this issue is already marked as "In progress".

**Comment by kunnark** [comment]
@turnerrainer this one is a copy of RIA's initial backlog https://github.com/buerokratt/Data-Anonymizer/issues/17 with no AC's related but needs to be done.

**Comment by vmugra** [comment]
@tarstarkvara please commit models to the repository as well.
