### ISSUE TITLE
Entity Recognition models based on regular expressions (regex)

### ISSUE THREAD

**Issue by kunnark** [buerokratt/Data-Anonymizer#78]
AS a Data Scientist
I WANT TO create logic and initial versions of regex-based engine
IN ORDER TO increase recall in finding entities

Acceptance Criteria:

- [x]  Regex-based logic is created and handed over to engineering side

**Comment by turnerrainer** [comment]
@kunnark 

1. User story is missing completely;
2. ACs are missing completely;
3. Regardless of the above, this issue is already marked as "In progress".

**Comment by vmugra** [comment]
@tarstarkvara please commit models to the repository as well.
