### ISSUE TITLE
Add new entity

### ISSUE THREAD

**Issue by kunnark** [buerokratt/Data-Anonymizer#89]
AS A Data Management Interface user
I WANT TO add a new entity to the database
IN ORDER TO use this entity later on training

Acceptance Criteria:

- [ ] I can add entity and the description to Postgres database via Ruuter `POST /entity` and ReSQL `POST /insert_entity`
- [ ] I can use UI to enter the data
- [ ]  If I enter the entity data then I have to confirm my input.

**Comment by kunnark** [comment]
@alimuhammadahmer please provide Ruuter and ReSQL endpoints for Acceptance Criteria.

**Comment by alimuhammadahmer** [comment]
@kunnark 
RUUTER: POST /entity
RESQL: POST /insert_entity
